package br.com.genius.view;

import br.com.genius.action.MainAction;
import br.com.genius.controller.MainController;
import br.com.genius.util.Util;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.JOptionPane;


public class Main extends javax.swing.JFrame 
{
    public Main()
    {
        initComponents();
        inicializar();
        carregaRecorde();
    }
    //
    private MainAction mainAction;
    private MainController mainController;
    //
//    private Color Util.Util.COR_BOTAO_1 = new Color(0, 100, 0);
//    private Color Util.Util.COR_BOTAO_2 = new Color(0, 0, 100);
//    private Color Util.Util.COR_BOTAO_3 = new Color(100, 0, 0);
//    private Color Util.Util.COR_BOTAO_4 = new Color(100, 100, 0);
//    //
//    private Color Util.Util.COR_BOTAO_1_CLICADO = Color.green;
//    private Color Util.Util.COR_BOTAO_2_CLICADO = Color.blue;
//    private Color Util.Util.COR_BOTAO_3_CLICADO = Color.red;
//    private Color Util.Util.COR_BOTAO_4_CLICADO = Color.yellow;
    //
    private int pontos = 0;
    private int hiScore = 0;

    public void mostraRecorde()
    {

        if (pontos > hiScore) {
            lblRecorde.setForeground(Color.blue);
        }

        lblRecorde.setText("Recorde: " + (pontos <= hiScore ? hiScore : pontos));

    }

    public void incrementaPontos()
    {
        pontos++;
        mostraPontos();
        mostraRecorde();
    }

    public void piscaSucesso()
    {

        Util.piscaComponente(this.jPanel1, Color.green);

    }

    public void piscaErro()
    {

        Util.piscaComponente(this.jPanel1, Color.red);

    }

    public void zeraPontos()
    {
        pontos = 0;
        mostraPontos();
    }

    private void mostraPontos()
    {

        lblPontos.setText("" + pontos);

    }

    public AbstractButton getBotao1()
    {
        return botao1;
    }

    public AbstractButton getBotao2()
    {
        return botao2;
    }

    public AbstractButton getBotao3()
    {
        return botao3;
    }

    public AbstractButton getBotao4()
    {
        return botao4;
    }

    public void inicializar()
    {

        botao1.setBackground(Util.COR_BOTAO_1);
        botao2.setBackground(Util.COR_BOTAO_2);
        botao3.setBackground(Util.COR_BOTAO_3);
        botao4.setBackground(Util.COR_BOTAO_4);
        //
        this.mainController = new MainController(this);
        this.mainAction = new MainAction(mainController);
        //
        removeListeners();
        adicionaListeners();
        //
        mostraPontos();
        mostraRecorde();

    }

    private void carregaRecorde() 
    {
        String recorde = Util.leArquivo();

        if (recorde != null && !recorde.isEmpty()) {
            hiScore = Integer.valueOf(recorde.trim());
        } else {
            hiScore = 0;
            Util.gravaArquivo("" + pontos);
        }
        mostraRecorde();
    }

    public void paintCampo(AbstractButton botao) 
    {
        if (botao.getName().equals("bt1")) {
            botao.setBackground(Util.COR_BOTAO_1_CLICADO);
        } else if (botao.getName().equals("bt2")) {
            botao.setBackground(Util.COR_BOTAO_2_CLICADO);
        } else if (botao.getName().equals("bt3")) {
            botao.setBackground(Util.COR_BOTAO_3_CLICADO);
        } else if (botao.getName().equals("bt4")) {
            botao.setBackground(Util.COR_BOTAO_4_CLICADO);
        }
    }

    public void unPaintCampo(AbstractButton botao) 
    {
        if (botao.getName().equals("bt1")) {
            botao.setBackground(Util.COR_BOTAO_1);
        } else if (botao.getName().equals("bt2")) {
            botao.setBackground(Util.COR_BOTAO_2);
        } else if (botao.getName().equals("bt3")) {
            botao.setBackground(Util.COR_BOTAO_3);
        } else if (botao.getName().equals("bt4")) {
            botao.setBackground(Util.COR_BOTAO_4);
        }
    }

    public void unPaintAll()
    {

        botao1.setBackground(Util.COR_BOTAO_1);
        botao2.setBackground(Util.COR_BOTAO_2);
        botao3.setBackground(Util.COR_BOTAO_3);
        botao4.setBackground(Util.COR_BOTAO_4);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJogue = new javax.swing.JLabel();
        botaoIniciar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblPontos = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        botao1 = new javax.swing.JButton();
        botao2 = new javax.swing.JButton();
        botao4 = new javax.swing.JButton();
        botao3 = new javax.swing.JButton();
        lblRecorde = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblJogue.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        lblJogue.setForeground(new java.awt.Color(2, 221, 16));
        lblJogue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        botaoIniciar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botaoIniciar.setText("INICIAR");
        botaoIniciar.setName("botaoIniciar"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Pontos:");

        lblPontos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPontos.setText(".");

        botao1.setFocusable(false);
        botao1.setName("bt1"); // NOI18N
        botao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao1ActionPerformed(evt);
            }
        });

        botao2.setFocusable(false);
        botao2.setName("bt2"); // NOI18N

        botao4.setFocusable(false);
        botao4.setName("bt4"); // NOI18N

        botao3.setFocusable(false);
        botao3.setName("bt3"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 93, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(botao1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(botao2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(botao3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(botao4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 93, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 27, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(botao1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botao2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(6, 6, 6)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(botao3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botao4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 27, Short.MAX_VALUE)))
        );

        lblRecorde.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblRecorde, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(botaoIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblJogue, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addGap(12, 12, 12)
                                .addComponent(lblPontos, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblJogue, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(lblPontos, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(7, 7, 7)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botaoIniciar)
                            .addComponent(lblRecorde))))
                .addGap(2, 2, 2))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-412)/2, (screenSize.height-340)/2, 412, 340);
    }// </editor-fold>//GEN-END:initComponents

    private void botao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao1ActionPerformed
    }//GEN-LAST:event_botao1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    public void habilitaBotaoIniciar(boolean habilita) {
        botaoIniciar.setEnabled(habilita);
    }

    public void showJogue(boolean jogar) {
        lblJogue.setText(jogar ? "Jogue!" : "");
    }

    public void finaliza(boolean isVencedor) {

        Util.gravaArquivo(pontos >= hiScore ? "" + pontos : "" + hiScore);



        if (isVencedor) {
            JOptionPane.showMessageDialog(this, "Parabéns! \nVocê GANHOU!!!\n\n Total de Pontos: " + pontos + "\n " + (pontos >= hiScore ? "Você bateu um RECORDE! " + pontos : ""), "GANHOU!", JOptionPane.INFORMATION_MESSAGE);


            System.exit(0);
        } else {
            JOptionPane.showMessageDialog(this, "Você errou! \n Total de Pontos: " + pontos + "\n " + (pontos >= hiScore ? "Você bateu um RECORDE! " + pontos : ""), "ERROU!", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }


    }

    private void removeListeners() {
        botao1.removeMouseListener(mainAction);
        botao2.removeMouseListener(mainAction);
        botao3.removeMouseListener(mainAction);
        botao4.removeMouseListener(mainAction);
        //
        botaoIniciar.removeMouseListener(mainAction);
    }

    private void adicionaListeners() {
        botao1.addMouseListener(mainAction);
        botao2.addMouseListener(mainAction);
        botao3.addMouseListener(mainAction);
        botao4.addMouseListener(mainAction);
        //
        botaoIniciar.addMouseListener(mainAction);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao1;
    private javax.swing.JButton botao2;
    private javax.swing.JButton botao3;
    private javax.swing.JButton botao4;
    private javax.swing.JButton botaoIniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblJogue;
    private javax.swing.JLabel lblPontos;
    private javax.swing.JLabel lblRecorde;
    // End of variables declaration//GEN-END:variables
}
